sudo: required
services:
  - docker
language: java
script:
  - mvn clean install docker:build
  - docker-compose create
  - docker-compose start
  - sleep 180
  - docker-compose stop
  - SERVERS_STARTED=`docker-compose logs | grep "Server started" | wc -l`
  - [ SERVERS_STARTED -eq 3 ] && echo "OK"
