sudo: required
services:
  - docker
language: java
install:
  - mvn clean install docker:build
script:
  - docker network create iosrkeyvalue_default
  - docker network create iosrkeyvalue_iosr
  - docker-compose create
  - docker-compose start
  - sleep 360
  - docker-compose stop
  - docker-compose stop
  - docker-compose logs
  - ./scripts/check_docker.sh || exit 1
