sudo: required
services:
  - docker
language: java
install:
  - mvn clean install docker:build
script:
  - docker network create iosrkeyvalue_iosr
  - docker-compose create
  - docker-compose start
  - ./verify.sh
  - docker-compose stop
  - docker-compose logs
