sudo: required
services:
  - docker
language: java
script:
  - mvn clean install docker:build
  - docker network create iosrkeyvalue_iosr
  - docker-compose create
  - docker-compose start
  - sleep 180
  - docker-compose stop
  - SERVERS_STARTED=`docker-compose logs | grep "Server started" | wc -l`
  - echo ${SERVERS_STARTED}
